# Everything you need to know about configuring the CMS can be found here:-
# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: master # Branch to update (master by default)

media_folder: "assets/img/uploads" # Folder where user uploaded files should go

publish_mode: editorial_workflow # Enable drafts

collections: # A list of collections the CMS should be able to edit
  # POSTS
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - label: "Author"
        name: "author"
        widget: "select"
        options:
          - { label: "Dan Urbanowicz", value: "dan_urbanowicz" }
          - { label: "John Doe", value: "john_doe" }
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss"}
      - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Categories", name: "categories", widget: "string", required: false}
    # PAGES
 # - name: "page"
 #   label: "Page"
#     folder: "pages"
#     sort: "title:asc"
#     create: false
#     slug: "{{slug}}"
#     fields:
#       - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
#       - {label: "Title", name: "title", widget: "string", tagname: "h1"}
#       - {label: "Permalink", name: "permalink", widget: "hidden"}
#       - {label: "Section", name: "section", widget: "hidden", default: "{{name}}"}
#       - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
#       - {label: "Body", name: "body", widget: "markdown", required: false}
    # UNIQUE PAGES
  - name: "page"
    label: "Page"
    files:
      - label: "Homepage"
        name: "homepage"
        permalink: "/"
        file: "pages/index.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
          - {label: "Permalink", name: "permalink", widget: "hidden"}
          - {label: "Title", name: "title", widget: "string", tagname: "h1"}
          - {label: "Headline", name: "headline", widget: "markdown", required: false}
          - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
          - {label: "Second Paragraph", name: "second_paragraph", widget: "markdown", required: false}
          - {label: "Third Paragraph", name: "third_paragraph", widget: "markdown", required: false}
          - {label: "Services intro", name: "services_intro", widget: "markdown", required: false}
          - {label: "Advisory & Coaching", name: "advisory", widget: "markdown", required: false}
          - {label: "Strategic Branding", name: "branding", widget: "markdown", required: false}
          - {label: "Sales, Marketing & Communication", name: "sales", widget: "markdown", required: false}
          - {label: "Employee Alignment & Connection", name: "employee_alignment", widget: "markdown", required: false}
          - {label: "Customers intro", name: "customers_intro", widget: "markdown", required: false}
          - {label: "Customers - scenarios", name: "customers_scenarios", widget: "list", required: false, field: {label: Content, name: content, widget: string}}
          - {label: "Customers outro", name: "customers_ontro", widget: "markdown", required: false}
          - {label: "Cohesion", name: "cohesion", widget: "markdown", required: false}
          - {label: "Collaboration", name: "collaboration", widget: "markdown", required: false}
          - {label: "Clarity", name: "clarity", widget: "markdown", required: false}
          - {label: "Value", name: "value", widget: "markdown", required: false}
          - {label: "Hearts & Minds", name: "hearts", widget: "markdown", required: false}
          - {label: "Standing Out", name: "standingout", widget: "markdown", required: false}
          - label: "Family of Growth"
            name: "family"
            widget: "list"
            required: false
            fields:
              - {label: Title, name: title, widget: string}
              - {label: URL, name: url, widget: markdown}
              - {label: Logo, name: logo, widget: image}
          - label: "Testimonials"
            name: "testimonials"
            widget: "list"
            required: false
            fields:
              - {label: Content, name: content, widget: markdown}
              - {label: Name, name: name, widget: string}
      - label: "About"
        name: "about"
        permalink: "/about"
        layout: "page"
        section: "about"
        file: "pages/about.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
          - {label: "Permalink", name: "permalink", widget: "hidden"}
          - {label: "Title", name: "title", widget: "string", tagname: "h1"}
          - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
      
